version: '3.8'

services:
  ultra-grid:
    build: .
    container_name: ultra-grid-bot
    restart: always
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
      - ./grid_plan.csv:/app/grid_plan.csv
    
  dashboard:
    build: .
    container_name: ultra-grid-dashboard
    command: streamlit run dashboard.py
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state